### ISSUE TITLE
Support `lemma` on equal footing with `theorem`

### ISSUE THREAD

**Issue by grantpassmore** [AestheticIntegration/imandra-vscode#5]
Currently, it seems `lemma` isn't treated on equal footing with `theorem`, `let`, `type`, `verify`, etc. It should be.

![image](https://user-images.githubusercontent.com/4193912/44670652-e1c39c00-a9e8-11e8-96f3-e5e22a459e65.png)

**Comment by ewenmaclean** [comment]
do we want the same behaviour for the instance keyword? Could you let me know all the keywords that I should know about and their grouped patterns?

I have fixed this for lemma but will not release right now as there will be a problem (annotated in README) with updating the package version.

**Comment by grantpassmore** [comment]
Yes, should be the same for `instance`.
These should all be on equal footing:

`let`, `type`, `theorem`, `verify`, `lemma`, `instance`

**Comment by grantpassmore** [comment]
Closed by https://github.com/AestheticIntegration/imandra-vscode/commit/6c210211d87434fae2185698c819031231f9eafc

**Comment by grantpassmore** [comment]
Reopening as it seems we don't yet support `instance`

**Comment by grantpassmore** [comment]
`instance` is supported! Closing
