### ISSUE TITLE
Cmd-Click (goto definition) fails with wrong path

### ISSUE THREAD

**Issue by grantpassmore** [AestheticIntegration/imandra-vscode#7]
`Cmd+Click` on a definition gives an error, looking for the file in the wrong (global?) path.

For example, if I have an IML file in a workspace (under, e.g., `/Users/grant/AI/imandra-workspace/nat.iml`), and I `Cmd+Click` on an instance of a function which is defined within the file, I get the following error:

![image](https://user-images.githubusercontent.com/4193912/44730719-362d5100-aaa7-11e8-9cf6-3d3b72b75427.png)

It seems it's looking for `nat.ml` in the wrong place.

**Comment by grantpassmore** [comment]
Similarly, `peek definition` fails as well

**Comment by ewenmaclean** [comment]
I am trying to figure this out but I think it may well be this line:

https://github.com/freebroccolo/ocaml-language-server/blob/master/src/bin/server/session/indexer.ts#L57

which means we need our own version of ocaml-language-server in reality to make this work properly. I can of course add this to the upstream PR but of course we don't know how long that will take.

**Comment by grantpassmore** [comment]
Awesome investigative work. Hmm, maybe we just have to bite the bullet and fork?

**Comment by ewenmaclean** [comment]
Yep possibly. Let me see what's needed for the server stuff - what I could do is produce a custom reason plugin then depend on that if that's feasible in conjunction with the lean like stuff I need to figure out.
